name: Run Circuit Simulation and Upload PDF

on:
  push:
    branches:
      - main  # Passe den Branch an, wenn nötig

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
      # Checkout des Repositories
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Python einrichten
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Passe die Python-Version an deine Anforderungen an

      # Installiere Abhängigkeiten
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Stelle sicher, dass requirements.txt vorhanden ist

      # Simulation ausführen
      - name: Run Circuit Simulation
        run: python lly/global.py  # Pfad zu deinem Skript anpassen

      # PDF als Artefakt hochladen
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: simulation-output
          path: |
            output.pdf  # Passe den Dateinamen und Pfad an, falls nötig
